#!/bin/bash

SRC_DIR=$( dirname "$(realpath $0)" )

NAME=homeassistant

case $1 in

  create)
    CONFIG_DIR="$SRC_DIR/config"
    [ ! -d $CONFIG_DIR ] && mkdir "$CONFIG_DIR"
    docker create \
      --name $NAME \
      --privileged --restart=unless-stopped \
      -e TZ=$( cat /etc/timezone ) \
      -v "$CONFIG_DIR:/config" \
      -v $SRC_DIR/custom_components:/config/custom_components \
      -v $SRC_DIR/bin:/root/bin \
      -v /run/dbus:/run/dbus:ro \
      --network=host \
      ghcr.io/home-assistant/home-assistant
    ;;

  remove)
    docker rm $NAME
    ;;

  start|stop|restart)
    docker $1 $NAME
    ;;

  recreate)
    $0 remove
    $0 create
    ;;

  logs)
    docker logs -f $NAME
    ;;

  logs)
    sudo truncate -s 0 $(docker inspect --format='{{.LogPath}}' $NAME)
    ;;

  fake-tild|analyse-tild-state-data)
    docker exec -t $NAME /root/bin/$@
    ;;
  *)
    cat << EOF
Usage: $0 [command]
  Available commands:
    create                     Create docker container
    remove                     Remove docker container
    recreate                   Recreate docker container
    start                      Start docker container
    stop                       Stop docker container
    restart                    Restart docker container
    logs                       Show (and follow) docker container logs
    truncate-logs              Truncate docker container logs
    fake-tild                  Run fake Tild server
    analyse-tild-state-data    Analyse raw Tild server state data
EOF
esac
