refresh:

set_light_color:
    fields:
        color:
            required: true
            example: cyan
            selector:
                select:
                    translation_key: "color"
                    options:
                        - "cold"
                        - "blue"
                        - "lagoon"
                        - "cyan"
                        - "purple"
                        - "magenta"
                        - "pink"
                        - "red"
                        - "orange"
                        - "green"
                        - "favorite"
                        - "gradient sequence"
                        - "rainbow"
                        - "parade"
                        - "techno"

set_light_intensity:
    fields:
        intensity:
            required: true
            example: 25
            selector:
                select:
                    translation_key: "intensity"
                    options:
                        - "25"
                        - "50"
                        - "75"
                        - "100"
